[target.msp430-none-elf]
# For debugging
# runner = "msp430-elf-gdb -q -x mspdebug.gdb"
# For running
runner = "./run.bat"
# UNCOMMENT ON LINUX
#runner = "./run.sh"

rustflags = [
    "-C", "link-arg=-nostartfiles",
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-lgcc",
    "-C", "link-arg=-mcpu=msp430",

    # Even though this chip has a HW multiplier, enabling it causes link errors, so we'll link the software multiplier for now
    #"-C", "link-arg=-lmul_none",
    "-C", "link-arg=-lmul_f5",
    "-C", "link-arg=-Wl,--allow-multiple-definition", # Prevent __muldi3 dupe errors
]

[build]
target = "msp430-none-elf"
# UNCOMMENT ON LINUX TO ADD msp430-gcc TO PATH
#rustc-wrapper = "./rustc_wrapper.sh"

[unstable]
# MSP430 doesn't come with libcore compiled already. But when it does, this
# key can be removed.
build-std = ["core"]
